### ISSUE TITLE
Unintended Changes in SIF_Metadata

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM27#49]
SIF_Metadata/LifeCycle/Created/Creators/Creator/Creator:  2.8 introduces redundant "Creator" element.
SIF_Metadata/RightsElements/RightsElements:  2.8 introduces extra "RightsElements" peer to "RightsElement."

Please correct.
<img width="1186" alt="2_7_lifecycle" src="https://user-images.githubusercontent.com/10967355/27847749-80ecf662-60f4-11e7-896b-b7091f90a18a.png">
<img width="1360" alt="2_8_lifecycle" src="https://user-images.githubusercontent.com/10967355/27847747-80ec2516-60f4-11e7-80fc-4758398bc8f6.png">
<img width="746" alt="2_7_rightselements" src="https://user-images.githubusercontent.com/10967355/27847750-80ed7a2e-60f4-11e7-9ea7-3a2fcd4c6a0b.png">
<img width="798" alt="2_8_rightselements" src="https://user-images.githubusercontent.com/10967355/27847748-80ec73cc-60f4-11e7-84f6-98a4015cd80c.png">

**Comment by ajackl** [comment]
Agreed.

**Comment by tqwhite** [comment]
This appears to be a simple error. Should be fixed.

**Comment by vinceparedes** [comment]
Fixed. A missing anchor tag and description was also found and fixed.

**Comment by 4pins** [comment]
Confirmed!
