### ISSUE TITLE
BusPositionInfos Ampersand

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM27#50]
Could we try to escape the ampersand in the following description & -> &amp;
"Id of the hardware unit on the bus that tracks & reports location and status..."

**Comment by 4pins** [comment]
FYI:  If it is already and escaped &amp; please use the word "and" instead.

**Comment by ajackl** [comment]
AGreed

**Comment by tqwhite** [comment]
I hate special characters!!!!

**Comment by vinceparedes** [comment]
I think best practice should be not to use ampersands in text.

**Comment by vinceparedes** [comment]
It was escaped. Changed to the word and. There are 20 other instances of ampersands but they are parts of titles.
