### ISSUE TITLE
Sif Characteristics are missing from all elements on all objects

### ISSUE THREAD

**Issue by tqwhite** [Access4Learning/NADM27#51]
![screen shot 2017-07-05 at 5 49 46 pm](https://user-images.githubusercontent.com/28464/27888197-697e429a-61aa-11e7-8562-47038ddf2d2e.png)

**Comment by 4pins** [comment]
Vince is working diligently on this feature, it will be in order before we release.

**Comment by ajackl** [comment]
Agreed.

**Comment by tqwhite** [comment]
Win!

**Comment by vinceparedes** [comment]
done. in review.
