### ISSUE TITLE
Unexpected new attribute in BusPositionInfo

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM27#52]
​/BusPositionInfos​/BusPositionInfo​/RouteStatus​/Status​/@BusRouteDetailRefId does not appear in the published 2.7M schema.  However it also doesn't seem nonsensical to include it here.  Is this a post release addition or purely unintentional?
<img width="769" alt="2_7_busroutedetailrefid" src="https://user-images.githubusercontent.com/10967355/27892241-68d95448-61b3-11e7-81cb-5e00317e4b46.png">
<img width="970" alt="2_8_busroutedetailrefid" src="https://user-images.githubusercontent.com/10967355/27892285-ab52bcec-61b3-11e7-820c-4c0be53286c4.png">

**Comment by ajackl** [comment]
I am really not sure of this.  It might be useful to talk to MA and see if they use BusRouteStatusStatusType.  It is unclear to me if that will keep this from being used by anyone using a simpler transportation system.  

I have no memory of any discussion on changing this object.

Does anyone know?

**Comment by tqwhite** [comment]
Unless this is response to an identified need, I am mildly opposed to adding new features to 2.8.

**Comment by 4pins** [comment]
Unless Alex finds something, I am with TQ II.  Let's drop/not add this one.

**Comment by vinceparedes** [comment]
My guess is that it is used in Australia and may have found its way into our spec. Many of their objects are exactly the same as the NA objects, except for ones that have been further developed. If we had the International Data Model group still working this could have been presented to the NA board. We would have argued against making it an attribute versus making it an element. 

It has been removed.
