### ISSUE TITLE
Unintended Changes in Demographics

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM27#54]
Demographics​/CountriesOfCitizenship​/CountriesOfCitizenship
Should not exist (note the plural)!
Demographics​/EnglishProficiency​/OtherCodeListType
Should not have been renamed (from OtherCodeList).
<img width="1047" alt="2_7_demographics" src="https://user-images.githubusercontent.com/10967355/27893318-d828691e-61b9-11e7-9980-48c4e3144b76.png">
<img width="761" alt="2_8_demographics" src="https://user-images.githubusercontent.com/10967355/27893324-e202ac42-61b9-11e7-9b0f-ec60e82592bb.png">

**Comment by ajackl** [comment]
Agreed.

**Comment by tqwhite** [comment]
Should be fixed.

**Comment by vinceparedes** [comment]
Again, AU tracks multiple citizenship while NA (US) only cares about one. Should also add Countries of Residency to the list. I will check this.

**Comment by vinceparedes** [comment]
Oops. I get it. A typo.

**Comment by vinceparedes** [comment]
Both of these have been corrected.
