### ISSUE TITLE
Unexpected new element ContactFlags

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM27#55]
​/StudentContacts​/StudentContact​/ContactFlags​/Other
Appears to be new, but makes perfect sense.
<img width="561" alt="2_7_contactflags" src="https://user-images.githubusercontent.com/10967355/27894783-2fa9cd0a-61c3-11e7-81f8-1bd350f15220.png">
<img width="584" alt="2_8_contactflags" src="https://user-images.githubusercontent.com/10967355/27894788-3641a08e-61c3-11e7-8002-34ec43aa40b5.png">

**Comment by ajackl** [comment]
Agreed.  Let's keep it.

**Comment by tqwhite** [comment]
And it's harmless. Keep.

**Comment by 4pins** [comment]
Good work!  Closing as no change is needed.
