### ISSUE TITLE
​StudentDemographicRecords​ OtherIdList not a list

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM27#56]
​/StudentDemographicRecords​/StudentDemographicRecord​/StudentPersonalData​/OtherIdList
Should have children and those children should have the Type attribute not the list.
<img width="605" alt="2_7_otheridlist" src="https://user-images.githubusercontent.com/10967355/27895079-f42e9a56-61c4-11e7-9f9e-f36fded2c36d.png">
<img width="487" alt="2_8_otheridlist" src="https://user-images.githubusercontent.com/10967355/27895080-f8fdccdc-61c4-11e7-8970-3ce4d54f2f4d.png">

**Comment by ajackl** [comment]
Agreed.

**Comment by tqwhite** [comment]
This is clearly an error that should be fixed.

**Comment by vinceparedes** [comment]
Fixed (I think). Somebody should check this one out.
