### ISSUE TITLE
SpecialEducation ServicesFundingSource OtherCodeList unexpectedly fixed

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM27#57]
​/StudentSpecialEducationRecords​/StudentSpecialEducationRecord​/StudentPlacementList​/StudentPlacementData​/ServiceFundingSources​/ServiceFundingSource​/OtherCodeList​/OtherCode
and
/StudentSpecialEducationSummarys​/StudentSpecialEducationSummary​/StudentPlacementList​/StudentPlacementData​/ServiceFundingSources​/ServiceFundingSource​/OtherCodeList​/OtherCode
Were missing in 2.7 (but not there immediate parent).
<img width="532" alt="2_7_servicefundingsource" src="https://user-images.githubusercontent.com/10967355/27895342-120ef212-61c7-11e7-8f7f-0b02121cee94.png">
<img width="1020" alt="2_8_servicefundingsource" src="https://user-images.githubusercontent.com/10967355/27895346-1720b92a-61c7-11e7-8e03-5ab66247d003.png">

**Comment by ajackl** [comment]
I hate these because it seems like a no brainer to say:  Yes- they should be there.  We are still maintaining the "Other Code List" Structure right?  We haven't designed that out for some reason?  

I think we should add it in to 2.8

**Comment by 4pins** [comment]
The only reason to not accept this change would be if someone said, "Oh no, that OtherCodeList is special and totally different from all the others.  We did it because..."  I believe it is correct as is, however others should come to that conclusion as well before we just let it slide.

**Comment by tqwhite** [comment]
Am I correct in understanding that this makes the OtherCodeList mirror other similar lists?

**Comment by 4pins** [comment]
Yes, TQ II that is exactly right.  It seems this OtherCodeList wasn't given the appropriate (complex) type and that has since been fixed.

**Comment by vinceparedes** [comment]
I agree. This was a mistake that when caught would go into an errata and then be corrected in the next version. I guess there should be a note to this effect in the 2.8 Spec under "whats new".  All these issues should be reviewed by the person who writes that section.
