### ISSUE TITLE
New Redundant Promotion Element in StudentSchoolEnrollment

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM27#62]
Last structural issue!
/StudentSchoolEnrollments/StudentSchoolEnrollment/PromotionInfo/Promotion/Promotion
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/10967355/29851140-5966f0d8-8ce7-11e7-836d-babafbb91499.png">
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/10967355/29851167-7f6660ac-8ce7-11e7-8430-b58f355a91ec.png">

**Comment by vinceparedes** [comment]
Done.
