### ISSUE TITLE
Energy Usage Characteristics

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM27#64]
Note:  This is the only issue found around characteristics in SIF (NA) 2.8 after checking thousands of fields.  There were some other warnings, all of which can be related to differences between the SIF 2 and SIF 3 data models in North America.

Warning: Schema mandatory element /EnergyUsages/EnergyUsage/DataSource/ReadingDataList/ReadingData/ReadingList/Reading/@IntervalIndex has optional characteristics, 'M' or 'Q' expected, "OR" found.

I believe this attribute simply got its parent's/element's SIF characteristics.  Do others agree?

<img width="733" alt="image" src="https://user-images.githubusercontent.com/10967355/29884932-cdfd61a2-8d69-11e7-9896-b52b42130b2c.png">

**Comment by tqwhite** [comment]
I forget what M and Q represent but having the interval optional seems like it would be a mistake. Without the interval, the 'reading' would be meaningless - is it X units per month, year, century?

Am I missing the point?

**Comment by 4pins** [comment]
Yes, unfortunately you are missing the point.
Point of order, M means Mandatory and Q means Required.
The Interval and other needed information are peers with the ReadingList (not pictured).
What I believe is the issue, is the IntervalIndex is correctly a Mandatory attribute marked incorrectly as Optional and Repeatable (which is correct for its immediate parent).
Hope this helps!

**Comment by tqwhite** [comment]
Not sure what I missed but it sounds like we agree that the designation of the interval as optional is not correct.

**Comment by ajackl** [comment]
I think this is fine.  I suspect it did just inherit it and it is certainly too small to go back to anyone with.  IMO.  I say let it ride.

**Comment by rpp9999** [comment]
I agree.  I believe we have a developing consensus - to let this go, if by doing so we avoid a lot of rework over a small detail.

**Comment by tqwhite** [comment]
Is this really a lot of rework? I'd have imagined it is a twelve second fix.

**Comment by 4pins** [comment]
@tqwhite Yes, particularly for a SIF 2 data model, it restarts an intensive process involving multiple people.  Assuming we let this go, we will leave this issue open and note it in the releases errata, so we don't lose track of it.

**Comment by tqwhite** [comment]
I love errata. It's a word that sounds so obscure but refers to the main product of human intelligence - after action apologies for mistakes.

FTW!!

**Comment by rpp9999** [comment]
I vote to proceed as proposed.

**Comment by tqwhite** [comment]
I'm with Roger.

**Comment by vinceparedes** [comment]
xml does not allow attributes to be repeatable. Also doesn’t make sense in this case. I could easily remove the OR and replace with M. 

------------------------------------
Vince Paredes
vinceparedes@gmail.com
512-785-7116

**Comment by tqwhite** [comment]
OH!! Now I'm with Vince!! I'd much rather it be correct than to have a chance to issue errata.

**Comment by 4pins** [comment]
@vinceparedes Feel free to change it in the input, that is a quick fix and we could close this ticket.
@tqwhite We are looking at a sizeable chuck (about a day) of work to republish 2.8 for two characters that might confuse a human, the ROI isn't here unless that it what it takes to get it approved.

**Comment by vinceparedes** [comment]
Okay. 

Do you want this one to still say draft? If not I also need the publish month (Aug. or Sept. ?) for the publishable draft. 

Let me know. 

------------------------------------
Vince Paredes
vinceparedes@gmail.com
512-785-7116

**Comment by 4pins** [comment]
@vinceparedes A non-draft labeled copy would be handy.  It should go public in the middle of September so let's go with that as the official month.  Then I can carry this forward regardless of the Technical Board's decision.

**Comment by tqwhite** [comment]
I have never been comfortable with 'almost correct' but accept your judgment that this isn't worth the trouble.

**Comment by rpp9999** [comment]
I second TQ's sentiment.

**Comment by 4pins** [comment]
I third TQ's sentiment.

Maybe we should look at this like a dress rehearsal.  It looks like the real thing, but we are still open to tweaks.  For-instance this release candidate is the first time we have published the collections.xsd file actually bundled with all of the various schema packages.  Under SIF 2 we have never published 100% valid schemas and this release is no exception.  Maybe we challenge people to try this version with their code generator or SIF 3 framework, then vote.  If we wind up fixing something else anyway, this will come along for the ride.

**Comment by vinceparedes** [comment]
Changed "OR" to "M".
